version: "3.2"

services:
  jupyter:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - "8887:8888"
    volumes:
      - type: bind
        source: ./resources
        target: /home/jupuser/resources
      - type: bind
        source: ./solutions
        target: /home/jupuser/solutions
      - type: bind
        source: ./datasets
        target: /home/jupuser/datasets
      - type: bind
        source: ./notebooks
        target: /home/jupuser/notebooks

    command: [ "bash", "-c", "jupyter lab --notebook-dir /home/jupuser/  --ip 0.0.0.0 --no-browser" ]
