version: "3.2"

services:
  jupyter:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - "8887:8888"
      - "8890-8899:8890-8899" # a bunch of ports to run multiple (10) bokeh servers :P
    environment:
      - BOKEH_ALLOW_WS_ORIGIN=127.0.0.1:8887,localhost:8887
      - DATA=/data/vanilla/
      - INTERIM=/data/interim/
      - PROCESSED=/data/processed/
    volumes:
      - type: bind
        source: ./resources
        target: /home/jupuser/resources
      - type: bind
        source: ./solutions
        target: /home/jupuser/solutions
      - type: bind
        source: ./datasets
        target: /home/jupuser/datasets
      - type: bind
        source: ./notebooks
        target: /home/jupuser/notebooks

    command: [ "bash", "-c", "jupyter notebook --notebook-dir /home/jupuser/  --ip 0.0.0.0 --no-browser" ]
